DEFAULT_ENCODING = 'utf8'

JUPYTER_LINE_LEN = 120
LONG_LINE_LEN = 900
DEFAULT_LINE_LEN = JUPYTER_LINE_LEN

EMPTY = ''
SPACE = ' '
DOT = '.'
COMMA = ','
COLON = ':'
SEMICOLON = ';'
STAR = '*'
CROSS = 'x'
PIPE = '|'
PLUS = '+'
MINUS = '-'
UNDER = '_'
EQUAL = '='
TILDA = '~'
SLASH = '/'
BACKSLASH = '\\'

ALL = STAR
COVERT = STAR * 3
DEFAULT_STR = MINUS
ITEM = MINUS
BULLET = STAR
DEL = CROSS
ABOUT = TILDA
FILL_CHAR = SPACE
REPR_DELIMITER = SPACE
NOT_SET = UNDER
PROTECTED = UNDER
SHORT_CROP_SUFFIX = UNDER
CROP_SUFFIX = DOT * 2
ELLIPSIS = DOT * 3
EQUALITY = EQUAL * 2
TITLE_PREFIX = EQUAL * 3
SMALL_INDENT = SPACE * 2
TAB_INDENT = SPACE * 4
ITEMS_DELIMITER = COMMA + SPACE
DEFAULT_ITEMS_DELIMITER = ITEMS_DELIMITER
IDS_DELIMITER = PIPE

TAB_CHAR, TAB_SUBSTITUTE = '\t', ' -> '
RETURN_CHAR, RETURN_SUBSTITUTE = '\r', ' <- '
PARAGRAPH_CHAR, PARAGRAPH_SUBSTITUTE = '\n', ' \\n '

OS_EXT_DELIMITER = DOT
OS_PARENT_PATH = DOT * 2
OS_PLACEHOLDER = ALL
PY_PLACEHOLDER = '{}'
PY_INDENT = TAB_INDENT
SQL_INDENT = TAB_INDENT
HTML_INDENT = TAB_INDENT
HTML_SPACE = '&nbsp;'

DEFAULT_TRUE_STR = 'Yes'
DEFAULT_FALSE_STR = 'No'
FALSE_VALUES = 'false', 'no', '0', '0.0', DEFAULT_STR, EMPTY
