FILL_CHAR = ' '
CROP_SUFFIX = '..'
SHORT_CROP_SUFFIX = '_'
LIST_DELIMITER = ', '

DEFAULT_STR = '-'
DEFAULT_TRUE_STR = 'Yes'
DEFAULT_FALSE_STR = 'No'
FALSE_VALUES = 'false', 'no', '-', '0', '0.0', ''

DEFAULT_PRECISION = 3
DEFAULT_LEN = 23

TAB_SYMBOL, TAB_SUBSTITUTE = '\t', ' -> '
PARAGRAPH_SYMBOL, PARAGRAPH_SUBSTITUTE = '\t', ' \\n '
